import json
import time
from pathlib import Path

import requests


BASE_URL = "http://127.0.0.1:8010/query"
OUTPUT_PATH = Path("scripts") / "smoke_results_multiturn_local_8010.json"
REVIEW_OUTPUT_PATH = Path("scripts") / "smoke_results_multiturn_local_8010_review.md"


SESSIONS = [
    {
        "name": "core_voyage_2306_exec",
        "queries": [
            "For voyage 2306, give an executive summary: vessel, route, financial result (PnL, revenue, expense), cargo grade, and any remarks on record.",
            "What about its remarks only?",
            "And who added them?",
            "Now show the expense items for that voyage.",
        ],
    },
    {
        "name": "core_vessel_stena_superior",
        "queries": [
            "Is Stena Superior performing well overall? Show its voyage history with PnL, identify best and worst voyage, and include any remarks for those voyages.",
            "Which is the best voyage only?",
            "And the worst one?",
            "What is the total revenue generated by this vessel?",
        ],
    },
    {
        "name": "core_high_revenue_low_pnl",
        "queries": [
            "Which voyages had high revenue but low or negative PnL? Show revenue, total expense, PnL, and expense-to-revenue ratio. Include remarks where recorded.",
            "Which one has the worst expense ratio?",
            "Show remarks for that one.",
            "Now show cargo grades for that same voyage.",
        ],
    },
    {
        "name": "core_scenario_comparison",
        "queries": [
            "Compare actual vs when-fixed results for voyages 1901, 1902, and 2301. Show PnL variance and TCE variance.",
            "Which of these changed the most on PnL variance?",
            "What about TCE variance only?",
            "Show only the worst variance.",
        ],
    },
    {
        "name": "core_module_type",
        "queries": [
            "For each module type (TC Voyage, Spot, etc), show average PnL, average revenue, voyage count, and most common cargo grade.",
            "Which module type has the highest average PnL?",
            "What about average revenue only?",
            "Show the cargo grade for the best one.",
        ],
    },
    {
        "name": "core_vessels_above_avg_pnl",
        "queries": [
            "Which vessels have the most voyages and above-average PnL? Show voyage count, average PnL, and most common cargo grade.",
            "Which vessel has the highest voyage count among these?",
            "Show the cargo grade for that vessel.",
            "What about the lowest average PnL in this result?",
        ],
    },
    {
        "name": "core_singapore_rank",
        "queries": [
            "For voyages that visited Singapore, rank by PnL and show cargo grades and vessel names. Include remarks if available.",
            "Which one has the highest PnL?",
            "Show remarks for that one.",
            "Now show cargo grades for that one.",
        ],
    },
    {
        "name": "core_port_calls",
        "queries": [
            "Show the 10 voyages with the most port calls. For each show vessel name, port count, PnL, and revenue.",
            "Which one has the most port calls?",
            "Show revenue for that one only.",
            "And the vessel name for the bottom one?",
        ],
    },
    {
        "name": "agg_total_pnl_vessel",
        "queries": [
            "Which vessel has earned the highest total PnL across all voyages?",
            "What about the top 3?",
            "Which one among these has the lowest total PnL?",
            "Show only the voyage count if available.",
        ],
    },
    {
        "name": "agg_avg_tce_per_vessel",
        "queries": [
            "What is the average TCE per vessel?",
            "Which vessel has the best average TCE?",
            "What about the lowest one?",
            "Show me the top 5 by average TCE.",
        ],
    },
    {
        "name": "agg_cargo_frequency",
        "queries": [
            "Which cargo grade appears most frequently across all voyages?",
            "What about the top 5 cargo grades?",
            "Which one has the highest count?",
            "Show the bottom one as well.",
        ],
    },
    {
        "name": "agg_voyage_count_each_vessel",
        "queries": [
            "How many voyages does each vessel have?",
            "Which vessel has the highest voyage count?",
            "What about the top 5 vessels by voyage count?",
            "Show the lowest one in that list.",
        ],
    },
    {
        "name": "agg_common_port",
        "queries": [
            "What is the most commonly visited port across all voyages?",
            "What about the top 5 ports?",
            "Which one has the highest count?",
            "Show the bottom one too.",
        ],
    },
    {
        "name": "agg_total_revenue",
        "queries": [
            "What is the total revenue across all voyages?",
            "Can you break that down by vessel?",
            "Which vessel contributes the most revenue?",
            "Show the top 5 if possible.",
        ],
    },
    {
        "name": "agg_busiest_ports",
        "queries": [
            "What are the busiest ports in the fleet?",
            "Which port is the busiest?",
            "Show the top 5 ports.",
            "What about the bottom one in that result?",
        ],
    },
    {
        "name": "agg_delayed_overall",
        "queries": [
            "How many voyages were delayed overall?",
            "Can you show delayed voyages as a list?",
            "Which delayed voyage has the highest PnL?",
            "Show remarks for that one if available.",
        ],
    },
    {
        "name": "agg_diverse_cargo_vessel",
        "queries": [
            "Which vessel has carried the most diverse set of cargo grades?",
            "What about the top 5 vessels?",
            "Which one has the highest voyage count among them?",
            "Show cargo grades for the top one.",
        ],
    },
    {
        "name": "agg_demurrage_wait_port",
        "queries": [
            "Ports with highest average demurrage wait time?",
            "Which port has the highest average demurrage wait time?",
            "Show the top 5 ports by this metric.",
            "What about the lowest one in that list?",
        ],
    },
    {
        "name": "agg_cargo_variance_actual_vs_whenfixed",
        "queries": [
            "Cargo grades with highest variance between ACTUAL and WHEN_FIXED PnL?",
            "Which cargo grade changed the most?",
            "Show the top 5 cargo grades by variance.",
            "What about the lowest one in that result?",
        ],
    },
    {
        "name": "agg_monthly_avg_pnl",
        "queries": [
            "Show average PnL trend month by month across all voyages.",
            "Which month has the highest average PnL?",
            "What about the lowest month?",
            "Show the top 3 months if possible.",
        ],
    },
    {
        "name": "vessel_metadata_identity_commercial",
        "queries": [
            "Show vessel id, IMO, and account code for vessel Elka Delphi.",
            "What is the hire rate, scrubber status, and market type of vessel Elka Delphi?",
            "Is vessel Elka Delphi operational?",
            "Give me commercial metadata for vessel Elka Delphi.",
        ],
    },
    {
        "name": "vessel_metadata_passage_consumption",
        "queries": [
            "List all passage types for vessel Elka Delphi.",
            "Show passage consumption profile for vessel Elka Delphi.",
            "Show default consumption rows for vessel Elka Delphi.",
            "For vessel Elka Delphi, show Ballast default speed, IFO, and MGO.",
        ],
    },
    {
        "name": "vessel_metadata_laden_rows",
        "queries": [
            "For vessel Elka Delphi, show Laden default speed, IFO, and MGO.",
            "Show all Ballast consumption rows for vessel Elka Delphi.",
            "Show all Laden consumption rows for vessel Elka Delphi.",
            "What about ballast defaults again?",
        ],
    },
    {
        "name": "vessel_metadata_non_passage",
        "queries": [
            "Show non-passage consumption for vessel Elka Delphi.",
            "For vessel Elka Delphi, show ifoLoad, ifoDischarge, ifoIdle, ifoHeat, ifoClean, ifoInert.",
            "For vessel Elka Delphi, show mgoLoad, mgoDischarge, mgoIdle, mgoHeat, mgoClean, mgoInert.",
            "Is this still the same vessel context?",
        ],
    },
    {
        "name": "vessel_metadata_tags_contract",
        "queries": [
            "Show tags for vessel Elka Delphi.",
            "Show contract history for vessel Elka Delphi.",
            "Show owner, duration, cp date, and delivery date for vessel Elka Delphi contract history.",
            "Who is owner of this vessel?",
        ],
    },
    {
        "name": "multi_voyage_vessel_metadata",
        "queries": [
            "For voyages 2301 and 2302, show operating status of corresponding vessels.",
            "For voyages 2301, 2302, 2303 show hire rate and scrubber.",
            "For voyages 2301 and 2302, show passage types for corresponding vessels.",
            "For voyages 2301 and 2302, show account code and market type.",
        ],
    },
    {
        "name": "voyage_metadata_fixture",
        "queries": [
            "What is the charterer, broker, and commission rates for voyage 2306?",
            "Show the CP date, CP quantity, demurrage rate, and laytime for voyage 2306.",
            "What cargo was carried on voyage 2306? Show grade, BL quantity, shipper, load port, and discharge port.",
            "Show the full route for voyage 2306 with ports, arrival and departure dates, and distances.",
        ],
    },
    {
        "name": "voyage_metadata_financial_lines",
        "queries": [
            "Break down the revenue lines for voyage 2306. Show freight, demurrage, and rebills separately.",
            "What are the expense items for voyage 2306? Include remarks for each line.",
            "Show bunker consumption and cost for voyage 2306 by grade.",
            "What remarks are on record for voyage 2306? Show remark text and who added it.",
        ],
    },
    {
        "name": "voyage_metadata_emissions_projected",
        "queries": [
            "What is the CII band, CO2, SOx, and NOx for voyage 2306?",
            "Show the projected financials for voyage 2306 - PnL, revenue, TCE, expenses, bunkers, port cost, and commission.",
            "What about remarks only for that voyage?",
            "And who added them?",
        ],
    },
    {
        "name": "vessel_ranking_ops",
        "queries": [
            "Which vessels are currently operating?",
            "Which vessels have the highest hire rate?",
            "Which vessels have scrubbers?",
            "How many vessels are non-scrubber?",
        ],
    },
    {
        "name": "vessel_ranking_speeds_pool",
        "queries": [
            "Which vessel has the highest default ballast speed?",
            "Which vessel has the highest default laden speed?",
            "Which vessels are in the short pool?",
            "Which vessels have the longest current contract duration?",
        ],
    },
    {
        "name": "vessel_ranking_finance",
        "queries": [
            "Which vessel has the highest voyage count?",
            "Which voyage had the highest profit or PnL?",
            "Which vessel has the best average TCE?",
            "Show me the top vessels by number of voyages.",
        ],
    },
]


def main() -> None:
    OUTPUT_PATH.parent.mkdir(exist_ok=True)
    results = []
    run_tag = int(time.time())

    for session in SESSIONS:
        session_id = f"smoke-multiturn-{run_tag}-{session['name']}"
        for index, query in enumerate(session["queries"], start=1):
            started = time.time()
            item = {
                "session": session["name"],
                "index": index,
                "query": query,
            }
            try:
                response = requests.post(
                    BASE_URL,
                    json={"query": query, "session_id": session_id},
                    timeout=120,
                )
                data = response.json()
                item.update(
                    {
                        "status_code": response.status_code,
                        "intent_key": data.get("intent_key"),
                        "answer": data.get("answer"),
                        "clarification": data.get("clarification"),
                        "trace": data.get("trace"),
                        "slots": data.get("slots"),
                        "dynamic_sql_used": data.get("dynamic_sql_used"),
                    }
                )
            except Exception as exc:
                item["error"] = str(exc)
            item["elapsed_sec"] = round(time.time() - started, 2)
            results.append(item)
            print(
                json.dumps(
                    {
                        "session": item["session"],
                        "index": item["index"],
                        "intent_key": item.get("intent_key"),
                        "status_code": item.get("status_code"),
                        "error": item.get("error"),
                        "elapsed_sec": item["elapsed_sec"],
                    },
                    ensure_ascii=True,
                ),
                flush=True,
            )

    OUTPUT_PATH.write_text(json.dumps(results, indent=2), encoding="utf-8")
    review_lines = [
        "# Multi-turn Smoke Review",
        "",
        f"- Base URL: `{BASE_URL}`",
        f"- Total results: `{len(results)}`",
        "",
    ]
    current_session = None
    for item in results:
        if item["session"] != current_session:
            current_session = item["session"]
            review_lines.extend(
                [
                    f"## Session: `{current_session}`",
                    "",
                ]
            )
        review_lines.extend(
            [
                f"### Turn {item['index']}",
                f"- Query: `{item['query']}`",
                f"- Status: `{item.get('status_code')}`",
                f"- Intent: `{item.get('intent_key')}`",
                f"- Elapsed: `{item.get('elapsed_sec')}` sec",
                f"- Slots: `{json.dumps(item.get('slots'), ensure_ascii=True)}`",
                "",
                "#### Response",
                "",
                "```text",
                str(item.get("answer") or ""),
                "```",
                "",
            ]
        )
        if item.get("clarification"):
            review_lines.extend(
                [
                    "#### Clarification",
                    "",
                    "```text",
                    str(item.get("clarification") or ""),
                    "```",
                    "",
                ]
            )
        if item.get("error"):
            review_lines.extend(
                [
                    "#### Error",
                    "",
                    "```text",
                    str(item.get("error") or ""),
                    "```",
                    "",
                ]
            )
    REVIEW_OUTPUT_PATH.write_text("\n".join(review_lines), encoding="utf-8")
    print(f"WROTE {OUTPUT_PATH} {len(results)} results", flush=True)
    print(f"WROTE {REVIEW_OUTPUT_PATH}", flush=True)


if __name__ == "__main__":
    main()
